FIN_FIELDS = """CERT REPDTE NAME STALP BKCLASS CB RSSDHCR SPECGRP
ASSET DEP DEPDOM DEPI DEPNI LNLSGR LNLSNET LNRE LNRECONS LNREMULT LNRENRES LNRENROW LNRENROT LNREAG LNRERES LNCI BRO SC ERNAST LNATRES
FREPP OTHBRF SUBND LIAB COREDEP LNRECNFM LNRECNOT FREPO CHBALI SCHA SCAF
EQ RBCT1J RBCT1 RBCT2 RBC RBC1AAJ RBCRWAJ RBC1RWAJ RBCT1CER
INTINC EINTEXP NIM NETINC ILNLS EDEP ELNLOS
NIMY INTEXPY INTINCY ROA ROE LNLSDEPR NCLNLSR BROR EEFFR NTLNLSR
NCLNLS P9LNLS NALNLS NCRENRES NCREMULT NCRECONS NCRERES NCREAG P3LNLS NTLNLS NTRENRES NTREMULT NTRECONS NUMEMP""".split()
